import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Trophy, Star, Users, Zap, TrendingUp, Award } from "lucide-react";

const AchievementsSection = () => {
  const achievements = [
    {
      icon: Trophy,
      title: "Revenue Generation",
      value: "₹10L+",
      description: "Total revenue generated by our startups",
      color: "text-success"
    },
    {
      icon: Star,
      title: "Success Rate",
      value: "100%",
      description: "Startups generating revenue",
      color: "text-primary"
    },
    {
      icon: Users,
      title: "Active Members",
      value: "50+",
      description: "Passionate entrepreneurs in our community",
      color: "text-accent"
    },
    {
      icon: Zap,
      title: "Startups Launched",
      value: "2+",
      description: "Successful ventures currently running",
      color: "text-primary"
    }
  ];

  const milestones = [
    {
      year: "2023",
      title: "Society Founded",
      description: "Startup Society officially launched at KL University with 20 founding members"
    },
    {
      year: "2023",
      title: "First Startup Success",
      description: "Innovience launched and gained 1000+ users within first month"
    },
    {
      year: "2023",
      title: "Revenue Milestone",
      description: "Both startups achieved profitability and sustainable revenue streams"
    },
    {
      year: "2024",
      title: "Community Growth",
      description: "Expanded to 50+ active members with multiple new projects in pipeline"
    }
  ];

  return (
    <section id="achievements" className="py-20 bg-gradient-to-b from-background to-secondary/10">
      <div className="container mx-auto px-6">
        {/* Header */}
        <div className="text-center space-y-4 mb-16">
          <h2 className="text-4xl lg:text-5xl font-bold">
            Our <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">Achievements</span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            From ambitious ideas to profitable ventures – here's how we've grown and what we've accomplished together.
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-6 mb-20">
          {achievements.map((achievement, index) => (
            <Card key={index} className="gradient-card shadow-card border-0 text-center transition-smooth hover:shadow-glow hover:scale-105">
              <CardContent className="p-6 space-y-4">
                <div className={`w-12 h-12 mx-auto gradient-primary rounded-lg flex items-center justify-center`}>
                  <achievement.icon className="w-6 h-6 text-primary-foreground" />
                </div>
                <div className="space-y-2">
                  <p className={`text-3xl font-bold ${achievement.color}`}>{achievement.value}</p>
                  <h3 className="font-semibold text-card-foreground">{achievement.title}</h3>
                  <p className="text-sm text-muted-foreground">{achievement.description}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Timeline */}
        <div className="space-y-8">
          <div className="text-center space-y-2">
            <h3 className="text-3xl font-bold text-foreground">Our Journey</h3>
            <p className="text-muted-foreground">Key milestones that shaped our community</p>
          </div>

          <div className="max-w-4xl mx-auto">
            <div className="relative">
              {/* Timeline Line */}
              <div className="absolute left-1/2 transform -translate-x-0.5 h-full w-0.5 bg-gradient-to-b from-primary to-accent"></div>

              {/* Timeline Items */}
              <div className="space-y-12">
                {milestones.map((milestone, index) => (
                  <div key={index} className={`flex items-center ${index % 2 === 0 ? 'flex-row' : 'flex-row-reverse'}`}>
                    {/* Content */}
                    <div className={`w-5/12 ${index % 2 === 0 ? 'text-right pr-8' : 'text-left pl-8'}`}>
                      <Card className="gradient-card shadow-card border-0">
                        <CardContent className="p-6 space-y-3">
                          <div className="flex items-center space-x-2">
                            <Badge variant="outline" className="border-primary/20">
                              {milestone.year}
                            </Badge>
                            <Award className="w-4 h-4 text-primary" />
                          </div>
                          <h4 className="text-lg font-semibold text-card-foreground">{milestone.title}</h4>
                          <p className="text-sm text-muted-foreground">{milestone.description}</p>
                        </CardContent>
                      </Card>
                    </div>

                    {/* Timeline Node */}
                    <div className="w-2/12 flex justify-center">
                      <div className="w-4 h-4 bg-primary rounded-full border-4 border-background shadow-glow"></div>
                    </div>

                    {/* Spacer */}
                    <div className="w-5/12"></div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Recognition */}
        <div className="mt-20 text-center space-y-8">
          <h3 className="text-2xl font-bold text-foreground">Recognition & Support</h3>
          <div className="flex flex-wrap justify-center gap-8 items-center opacity-60">
            <div className="text-lg font-semibold text-muted-foreground">KL University</div>
            <div className="w-2 h-2 bg-muted-foreground rounded-full"></div>
            <div className="text-lg font-semibold text-muted-foreground">Innovation Cell</div>
            <div className="w-2 h-2 bg-muted-foreground rounded-full"></div>
            <div className="text-lg font-semibold text-muted-foreground">Student Affairs</div>
            <div className="w-2 h-2 bg-muted-foreground rounded-full"></div>
            <div className="text-lg font-semibold text-muted-foreground">Industry Partners</div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AchievementsSection;